#!/usr/bin/perl

#
# Copyright (C) 2019 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

use strict;
use esmith::ConfigDB;
use esmith::event;
use JSON;
use NethServer::ApiTools;
my $data = NethServer::ApiTools::readInput();
my $cdb = esmith::ConfigDB->open() || die("Could not open ConfigDB");
my $action = $data->{'action'};


if ($action eq 'configuration') {
    foreach my $prop (qw(
        MaxNbOfDomain
        MinHitBrowser
        MaxNbOfLoginShown
        MaxNbOfRefererShown
        MinHitKeyphrase
        MinHitDownloads
        MinHitOs
        Minute
        MinHitFile
        DnsLookup
        MinHitDomain
        MaxNbOfBrowsersShown
        MaxNbOfDownloadsShown
        MaxNbOfPageShown
        skipPrivateIp
        MaxNbOfKeyphrasesShown
        MinHitHost
        MaxNbOfScreenSizesShown
        PdfReport
        status
        MinHitKeyword
        MinHitRefer
        MaxNbOfOsShown
        MinHitScreenSize
        MinHitLogin
        MaxNbOfRobotShown
        MaxNbOfHostsShown
        GeoIP
        MinHitRobot
        MaxNbOfKeywordsShown
        access
        SendReport
        Users
    )) {
        $cdb->set_prop('awstats', $prop, $data->{$prop});
    }

    esmith::event::set_json_log(1);
    my $success = esmith::event::event_signal('nethserver-awstats-update');
    if($success) {
        NethServer::ApiTools::success();
    } else {
       NethServer::ApiTools::error("EventError", "update_action_failed", 1550763562);
    }
}